### ISSUE TITLE
[Issue] Extension/firefox/openwpm.xpi invalid

### ISSUE THREAD

**Issue by baejaeho18** [spring-epfl/WebGraph#7]
To run the WebGraph, I followed the instructions [here](https://github.com/sandrasiby/OpenWPM/tree/webgraph#readme) to setup custom OpenWPM in my environment.
But in the progress of install script, "No such file" issue occurs as follow:
> $ ./install.sh
>  Creating / Overwriting openwpm conda environment.
>  Channels:
>  - conda-forge
>   - main
>   - defaults
>  Platform: linux-64
  Collecting package metadata (repodata.json): ...working... done
  Solving environment: ...working... done
  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  Installing pip dependencies: ...working... done
  Activating environment.
  Installing firefox.
  Installing for Linux
  tar (child): **target.tar.bz2: Cannot open: No such file or directory**
  tar (child): Error is not recoverable: exiting now
  tar: Child returned status 2
  tar: Error is not recoverable: exiting now
  mv: cannot stat 'firefox': No such file or directory
  rm: cannot remove 'target.tar.bz2': No such file or directory
  Firefox succesfully installed

As I read the [install-firefox.sh](https://github.com/sandrasiby/OpenWPM/blob/webgraph/scripts/install-firefox.sh), issued [link](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-release.revision.cda19fb46018c9cb8dc5e6127ebb2cfd04aa9be4.firefox.linux64-add-on-devel/artifacts/public/build/target.tar.bz2) was invalid
![image](https://github.com/user-attachments/assets/7ea6f989-fa15-4e94-b311-c23fc0b47ad5)

Maybe the website changes some pathes, so I look around firefox-ci-tc and found that the  FIREFOX_90_0_2_RELEASE(release version of script) doesn't exist any more.
Here is the link, 
https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-release.revision
![image](https://github.com/user-attachments/assets/07c330a4-e798-4d6f-abd0-28cae08ca00f)

So, what I want to know is the possible version of firefox service instead of  FIREFOX_90_0_2_RELEASE.
Or, could you share the used executable file during the experiment?

Thanks for sharing your great research

**Comment by baejaeho18** [comment]
Well, I solved this issue by find out legacy release of firefox from []()
However, I got other issue like below.
![image](https://github.com/user-attachments/assets/3d480f1f-e622-47af-aef8-26d1319b3c03)
Why does this file doesn't exist in repository? Does the '/tmp' directory made in runtime?

**Comment by sandrasiby** [comment]
Hi, as noted in the latest README update (first lines), we are in the process of fixing the OpenWPM compatibility issue (which is causing the errors you see). Meanwhile, please use the trained model on the drive link mentioned in the README.
